name: ZEUS Executor Auto Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install

    - name: Build do projeto
      run: npm run build

    - name: Commit de atualização automática
      run: |
        git config user.name "ZEUS Executor"
        git config user.email "zeus@executor.ai"
        echo "🧠 Auto update from ZEUS Executor" >> UPDATE.md
        git add UPDATE.md
        git commit -m "Auto commit from ZEUS Executor 🤖"
        git push
